apiVersion: apps/v1
kind: Deployment
metadata:
  name: "${{ values.name }}-adservice"
  labels:
    app: "${{ values.name }}-adservice"
spec:
  selector:
    matchLabels:
      app: "${{ values.name }}-adservice"
  template:
    metadata:
      labels:
        app: "${{ values.name }}-adservice"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice:v0.10.2
          ports:
            - containerPort: 9555
          env:
            - name: PORT
              value: "9555"
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            grpc:
              port: 9555
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            grpc:
              port: 9555
---
apiVersion: v1
kind: Service
metadata:
  name: "${{ values.name }}-adservice"
  labels:
    app: "${{ values.name }}-adservice"
spec:
  type: ClusterIP
  selector:
    app: "${{ values.name }}-adservice"
  ports:
    - name: grpc
      port: 9555
      targetPort: 9555
