apiVersion: apps/v1
kind: Deployment
metadata:
  name: "${{ values.name }}-paymentservice"
  labels:
    app: "${{ values.name }}-paymentservice"
spec:
  selector:
    matchLabels:
      app: "${{ values.name }}-paymentservice"
  template:
    metadata:
      labels:
        app: "${{ values.name }}-paymentservice"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice:v0.10.2
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
            - name: DISABLE_PROFILER
              value: "1"
          readinessProbe:
            grpc:
              port: 50051
          livenessProbe:
            grpc:
              port: 50051
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: "${{ values.name }}-paymentservice"
  labels:
    app: "${{ values.name }}-paymentservice"
spec:
  type: ClusterIP
  selector:
    app: "${{ values.name }}-paymentservice"
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
