apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "argocd-${{ values.name }}"
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "${{ values.gitops_repository }}"
    targetRevision: HEAD
    path: ./ecommerce/deployments
  destination:
    server: https://kubernetes.default.svc
    namespace: "${{ values.namespace }}"
  ignoreDifferences:
    - group: "*"
      jqPathExpressions:
        - '.imagePullSecrets[] | select(.name | contains("-dockercfg-"))'
      kind: ServiceAccount
    - group: "apps"
      kind: Deployment
      jqPathExpressions:
        - ".spec.template.spec.containers[].image"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
