apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    chains.tekton.dev/signed: "true"
  finalizers:
    - chains.tekton.dev/pipelinerun
  labels:
    tekton.dev/pipeline: clone-build-push
    backstage.io/kubernetes-id: "${{ values.name }}"
spec:
  params:
    - name: GIT_REPO
      value: "${{ values.source_repository }}"
    - name: IMAGE_NAME
      value: "${{ values.name }}:latest"
  pipelineRef:
    name: clone-build-push
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: source-repo
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: ocs-storagecluster-cephfs
          volumeMode: Filesystem
        status: {}
