apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: "${{ values.name }}"
    backstage.io/kubernetes-id: "${{ values.name }}"
  name: "${{ values.name }}"
spec:
  port:
    targetPort: 9080
  to:
    kind: Service
    name: "${{ values.name }}"
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
