apiVersion: v1
kind: Service
metadata:
  labels:
    app: "${{ values.name }}"
    backstage.io/kubernetes-id: "${{ values.name }}"
  name: "${{ values.name }}"
spec:
  ports:
    - name: http
      port: 9080
      targetPort: 9080
  selector:
    deployment: "${{ values.name }}"
