---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: "{{ name }}"
  labels:
    app: "{{ name }}"
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: "{{ name }}"
  labels:
    app: "{{ name }}"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "{{ name }}:latest"
  postCommit: {}
  resources: {}
  source:
    git:
      uri: "{{ source_repository }}"
      ref: "main"
    type: Git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: nodejs:16-ubi8
  triggers:
    - github:
        secret: "bWVobWVobWVo"
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: "{{ name }}"
  labels:
    app: "{{ name }}"
spec:
  template:
    spec:
      containers:
        - image: "{{ name }}:latest"
          name: "{{ name }}"
          securityContext:
            privileged: false
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources:
            limits:
              memory: "{{ memorylimit }}"
    metadata:
      labels:
        app: "{{ name }}"
  replicas: 1
  selector:
    app: "{{ name }}"
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - "{{ name }}"
        from:
          kind: ImageStreamTag
          name: "{{ name }}:latest"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ name }}"
  name: "{{ name }}"
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 3000
  selector:
    app: "{{ name }}"
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: "{{ name }}"
  name: "{{ name }}"
spec:
  port:
    targetPort: 3000
  to:
    kind: Service
    name: "{{ name }}"
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
